/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Player {
  Username: string;
  Game: string;
  TeamAffiliation: string;
  Img?: string;
  ClubStatus?: string;
  Description?: string;
  MainCharacter?: string;
  Rank?: string;
  Role?: string;
}
